### ISSUE TITLE
Add Grant round controls

### ISSUE THREAD

**Issue by marcj303** [playatech/weightlifter#19]
Add controls for different grant rounds. 
Admin should be able to create a grant round, set dates for users to apply and for judges to judge (prevent changes pre/post dates), set the grant round amount etc.

Landing page could automatically show current or upcoming grant round information and statistics. 

Users/judges dashboard should show the current grant round applications.

**Comment by itsrachelfish** [comment]
The controls for grant rounds is currently implemented as laravel environment variables which allow / disable specific features:
- Creation of new applications
- Submission of existing applications
- Judging

In the future we'll definitely want to make something more robust with automated deadlines.

**Comment by itsrachelfish** [comment]
Todo checklist for this feature:

- [ ] Create model / migration for rounds
- [ ] Set up forms for creating and editing rounds
- [ ] Automatically display basic round information on the home page
- [ ] Display detailed round information on the user dashboard
- [ ] Only allow applications to be created / submitted during a grant round
- [ ] Automatically assign applications to the current grant round
- [ ] Add options for judges to filter applications by grant round

**Comment by itsrachelfish** [comment]
This is finished now! Finally :D
