### ISSUE TITLE
Add funds field to application variables

### ISSUE THREAD

**Issue by marcj303** [playatech/weightlifter#34]
Add requested funds as an application field. This will make it easier to sort and find the funds for an application instead of trying to find it in the questions fields. We can also validate the funds requested are below the limits for that round (once round data is added).

**Comment by itsrachelfish** [comment]
This option should also be validated based against the minimum / maximum round options.

**Comment by itsrachelfish** [comment]
This is on production now, we should convert the existing budget data from the questions table to the new budget column before removing the original question.
