### ISSUE TITLE
Add ability for a user to retract/withdraw an application

### ISSUE THREAD

**Issue by marcj303** [playatech/weightlifter#37]
Some users applied before the deadline and submitted their application and then could not edit it prior to the deadline. A feature to retract an application would be useful, so we don't get multiple submissions for the same project to judge. A user may wish to withdraw during the scoring period (they can't do the project or have any other issue that requires them to withdraw). That would be important to know before final judging and project acceptance.

I think that the following would work:
1. retract button available to user once they submit
2. retract put the application back in the new state, removes any scores, ( not certain feedback should be kept or not.)
3. user resubmits application after making changes (if submissions are allowed).

**Comment by itsrachelfish** [comment]
@marcj303 Going to close this now since users can withdraw their applications.
