### ISSUE TITLE
A score is not saved if the user accepts the default

### ISSUE THREAD

**Issue by marcj303** [playatech/weightlifter#46]
If the user doesn't click in each criteria scoring form, a score is never recorded for that criteria.  This is common that the user accepts the default value displayed. 

A default score should be created for each criteria if the ajax doesn't save/create it.

**Comment by marcj303** [comment]
The saved and  default scores are passed to the view in reviewApplication(). That might be an ok place to create the default scores. Something like this:
 
```
         // Select all scores made by the current user
-        foreach($application->scores()->where('user_id', Auth::user()->id)->get() as $score)
+        foreach($criteria as $criterion)
         {
-            $scores[$score->criteria_id] = $score;
+            $scores[$criterion->id] = Score::firstOrNew(['application_id' => $application->id, 'criteria_id' => $criterion->id, 
         }
```

**Comment by itsrachelfish** [comment]
As a temporary measure I added some JS which autosaves scores as a judge is scrolling through the page, this way the default value will automatically be saved to the database.

Please double check to make sure this works with the scoring code you were working on and I can merge your new page into production.

That being said, we really should discuss in more detail what the requirements are for the final statistics that need to be provided. It would help a lot to think about what potential schema or behavior changes we'll need to make in the future.

I really should sleep now... :sleepy: :zzz:

**Comment by marcj303** [comment]
Thanks, I think that is a better and more consistent way. I was not comfortable with my solution. 
The save is being by on the js side if they answer the question or leave the default.

Since we haven't used this scoring method before, we are uncertain if it is going to be balanced as we expect or if we will need to see where it is a problem. So, I wanted to be able to display average per criteria and then drill down to all scores. Export to csv was the next step, as we can run some other models to prototype scoring if we need. I expect that there might be laravel or php for this already in the framework. 

Thanks for putting in the long hours on this.
